[package]
name = "elf-vt-patcher"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.40", features = ["derive"] }
clap-num = "1.2.0"
elf-utilities = "0.2.20"
goblin = "0.10.0"
object = {  version = "0.37.1", features = ["all"] }
regex = "1.11.1"
